nutellove/nutellove/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

from products import views as product_views
from . import views

urlpatterns = [
    # homepage
    path('', TemplateView.as_view(template_name="index.html"), name="index"),
    path('users/', include('users.urls', namespace="users")),
    path('products/', include('products.urls', namespace="products")),
    path(
        'legals/',
        TemplateView.as_view(template_name="legals.html"),
        name="legals"),
    path('admin/', admin.site.urls),
    path('search/', product_views.Search.as_view(), name='search'),
    # path('favorites/', views.UserFavoritesView.as_view(), name='favorites'),
]


if settings.DEBUG:  # pragma: no cover
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

nutellove/products/urls.py
from django.urls import path

from . import views  # import views so we can use them in urls.
from .models import Favorite, Brand, Category

# required for django 2.0
app_name = "products"

urlpatterns = [
    # what to display for url products/
    path('', views.listing),
    # what to display for url products/<id>
    path(
        '<int:product_id>',
        views.ProductDetail.as_view(),
        name='product_detail',
    ),
    # what to display for url products/search/?query=<query>
    path(
        'search/', views.Search.as_view(),
        name='search',
    ),
    # use a custom link to boorkmark products
    path(
        'bookmark/<int:product_id>',
        views.FavoriteView.as_view(model=Favorite),
        name="bookmark",
    ),
    # favorites/
    path(
        'favorites/',
        views.FavoriteView.as_view(model=Favorite),
        name="favorites",
    ),
    # brands/
    path(
        'brands/',
        views.BrandCategoryDetail.as_view(
            model=Brand,
        ),
        name="brands"
    ),
    # brands/<int:brand_id>
    path(
        'brands/<int:obj_id>',
        views.BrandCategoryDetail.as_view(
            model=Brand,
        ),
        name="brand_detail",
    ),
    path(
        'categories/',
        views.BrandCategoryDetail.as_view(
            model=Category,
        ),
        name="categories",
    ),
    # categories/<int:category_id>
    path(
        'categories/<int:obj_id>',
        views.BrandCategoryDetail.as_view(
            model=Category,
        ),
        name="category_detail",
    ),
]

nutellove/users/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

# required for django 2.0
app_name = "users"

urlpatterns = [
    path('', views.UserAccountView.as_view(), name='account'),
    path('register/', views.UserFormView.as_view(), name='register'),
    path('login/', auth_views.login, name='login'),
    path('logout/', auth_views.logout, {'next_page': '/'}, name='logout'),
    path('account/', views.UserAccountView.as_view(), name='account'),
]


if settings.DEBUG:  # pragma: no cover
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

nutellove/templates/shared/footer.html
<footer class="footer">
    <div class="container">
        <a href="{% url 'legals' %}" class="ml-5 text-muted">Mentions légales</a>
        <a href="{% url 'index' %}#contact" class="ml-5 text-muted">Contact</a>
    </div>
</footer>

nutellove/templates/shared/form_template.html
<!-- Template to call every fields of a form class inside an html form -->

{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <span class="text-danger small">{{ field.errors }}</span>
    </div>
    <label class="control-label col-sm-10">{{ field.label_tag }}</label>

    <div class="col-sm-12">
      <div class="input-group">
        {% render_field field|add_class:"form-control" %}
      </div>
    </div>
  </div>
{% endfor %}

nutellove/templates/shared/header.html
{% load static %}

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container nav-container">
    <a class="navbar-brand js-scroll-trigger" href="{% url 'index' %}"><object type="image/svg+xml" class="mr-2 align-top" height="30" width="50" data="{% static 'img/logo_pur_beurre.svg' %}" alt=""></object>Pur beurre</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        {% include 'shared/search_form_header.html' %}
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="{% url 'products:search' %}"><i class="fa fa-2x fa-search text-primary mb-3 sr-icons"></i></a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="{% if user.is_authenticated %} {% url 'users:account' %} {% else %}{% url 'users:login' %}{% endif %}"><i class="{% if user.is_authenticated %}fa fa-2x fa-user {% else %} fa fa-2x fa-user-plus {% endif %} text-primary mb-3 sr-icons"></i></a>
        </li>
        <!-- if user is auth then show favorites page, else go to registration -->
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="{% if user.is_authenticated %} {% url 'products:favorites' %} {% else %}{% url 'users:login' %}{% endif %}"><img height="35" src="{% static 'img/carrot.svg' %}" alt="Mes aliments"></a>
        </li>
        <!-- if user is auth then disconnect user, else do nothing -->
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'users:logout' %}"><i class="fa fa-2x fa-sign-out text-primary mb-3 sr-icons"></i></a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

nutellove/templates/shared/search_form.html
{% load i18n %}

<div class="container my-auto text-center">
  <div class="row">
    <div class="col-lg-8 mx-auto">
    <form action="{% url 'products:search' %}" method="get">
      <input type="text" name="query" class="form-control" placeholder="Essayez &laquo; Chocolat &raquo;...">
      <button class="btn mt-4 btn-primary">{% blocktrans %} Chercher {% endblocktrans %}</button>
    </form>
    </div>
  </div>
</div>

nutellove/templates/shared/search_form_header.html
{% load i18n %}

<li class="col-lg-6 mt-1">
  <form action="{% url 'products:search' %}" method="get">
    <div class="input-group header-input">
      <input type="text" name="query" class="form-control" placeholder="Chercher...">
      <div class="input-group-btn"><button type="submit" class="btn btn-primary btn-search h-100">{% blocktrans %} Go {% endblocktrans %}</button></div>
    </div>
  </form>
</li>