nutellove/nutellove/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

from products import views as product_views
from . import views

urlpatterns = [
    # homepage
    path('', TemplateView.as_view(template_name="index.html"), name="index"),
    path('users/', include('users.urls', namespace="users")),
    path('products/', include('products.urls', namespace="products")),
    path(
        'legals/',
        TemplateView.as_view(template_name="legals.html"),
        name="legals"),
    path('admin/', admin.site.urls),
    path('search/', product_views.Search.as_view(), name='search'),
    # path('favorites/', views.UserFavoritesView.as_view(), name='favorites'),
]


if settings.DEBUG:  # pragma: no cover
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

nutellove/products/urls.py
from django.urls import path

from . import views  # import views so we can use them in urls.
from .models import Favorite, Brand, Category

# required for django 2.0
app_name = "products"

urlpatterns = [
    # what to display for url products/
    path('', views.listing),
    # what to display for url products/<id>
    path(
        '<int:product_id>',
        views.ProductDetail.as_view(),
        name='product_detail',
    ),
    # what to display for url products/search/?query=<query>
    path(
        'search/', views.Search.as_view(),
        name='search',
    ),
    # use a custom link to boorkmark products
    path(
        'bookmark/<int:product_id>',
        views.FavoriteView.as_view(model=Favorite),
        name="bookmark",
    ),
    # favorites/
    path(
        'favorites/',
        views.FavoriteView.as_view(model=Favorite),
        name="favorites",
    ),
    # brands/
    path(
        'brands/',
        views.BrandCategoryDetail.as_view(
            model=Brand,
        ),
        name="brands"
    ),
    # brands/<int:brand_id>
    path(
        'brands/<int:obj_id>',
        views.BrandCategoryDetail.as_view(
            model=Brand,
        ),
        name="brand_detail",
    ),
    path(
        'categories/',
        views.BrandCategoryDetail.as_view(
            model=Category,
        ),
        name="categories",
    ),
    # categories/<int:category_id>
    path(
        'categories/<int:obj_id>',
        views.BrandCategoryDetail.as_view(
            model=Category,
        ),
        name="category_detail",
    ),
]

nutellove/users/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

# required for django 2.0
app_name = "users"

urlpatterns = [
    path('', views.UserAccountView.as_view(), name='account'),
    path('register/', views.UserFormView.as_view(), name='register'),
    path('login/', auth_views.login, name='login'),
    path('logout/', auth_views.logout, {'next_page': '/'}, name='logout'),
    path('account/', views.UserAccountView.as_view(), name='account'),
]


if settings.DEBUG:  # pragma: no cover
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

nutellove/products/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# coding: utf8


class Brand(models.Model):
    name = models.CharField(unique=True, max_length=500)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(unique=True, max_length=500)

    def __str__(self):
        return self.name


class Store(models.Model):
    name = models.CharField(unique=True, max_length=500)

    def __str__(self):
        return self.name


class Product(models.Model):
    code = models.BigIntegerField()
    url = models.URLField(null=False, unique=True)
    name = models.CharField(max_length=500)
    nutri_grade = models.CharField(null=True, max_length=1)
    cat = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
    )
    energy = models.IntegerField(null=True)
    fat = models.FloatField(null=True)
    carbs = models.FloatField(null=True)
    sugars = models.FloatField(null=True)
    fibers = models.FloatField(null=True)
    proteins = models.FloatField(null=True)
    salt = models.FloatField(null=True)
    img = models.URLField(null=True)
    img_small = models.URLField(null=True)
    last_modified_t = models.DateTimeField(null=False)
    brands = models.ManyToManyField(Brand, db_table="products_brands")
    stores = models.ManyToManyField(Store, db_table="products_stores")

    def __str__(self):
        return self.name


class Favorite(models.Model):

    substitute = models.ForeignKey(
        Product,
        related_name='products_substitute_set',
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        User,
        verbose_name="User",
        on_delete=models.CASCADE,
        default=0,
    )

nutellove/products/views.py
from random import randint

from django.contrib import auth
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from .models import Brand, Category, Product, Favorite
from django.utils.translation import gettext
from django.views import View

# Create your views here.


def listing(request):  # pragma: no cover
    """
    List all available products on a page
    """
    products = Product.objects.filter()[:9]

    title = gettext("Tous nos produits")

    context = {
        'products': products,
        'title': title,
        'paginate': True
    }

    return render(request, 'products/listing.html', context)


class ProductDetail(View):
    template_name = 'products/product_details.html'

    def get(self, request, product_id):
        """
        Used to display the details of a product
        """
        product = get_object_or_404(Product, pk=product_id)
        category = get_object_or_404(Category, pk=product.cat.id)
        brands = [brand.name for brand in product.brands.all()]
        stores = [store.name for store in product.stores.all()]

        context = {
            'product': product,
            'brands': brands,
            'stores': stores,
            'category': category,
        }

        return render(request, self.template_name, context)


class BrandCategoryDetail(View):  # pragma: no cover
    """
    Abstract class to display categories and details
    """
    obj = None
    model = None
    template_name = 'products/category_or_brand_details.html'

    def get(self, request, **kwargs):
        """
        Used to give details of a brand
        """
        user = auth.get_user(request)
        obj_id = kwargs.get('obj_id')

        if obj_id is None:
            objs = self.model.objects.all().order_by('name')

            if self.model == Brand:
                title = "Toutes les marques"
            elif self.model == Category:
                title = "Toutes les catégories"

            context = {
                'objs': objs,
                'title': title,
                'model': self.model.__name__,
            }

            return render(request, self.template_name, context)

        else:
            # get the object with the obj_id passed in the url
            obj = get_object_or_404(self.model, pk=obj_id)

            # conditionnals for text, can be updated I guess
            if self.model == Brand:
                products = Product.objects.filter(brands=obj.id)[:9]
                title = "Produits de la marque {}".format(obj.name)
            elif self.model == Category:
                products = Product.objects.filter(cat=obj.id)[:9]
                title = "Produits de la catégorie {}".format(obj.name)

            # check if user is not anonymous
            if user.username != "":
                for product in products:
                    if Favorite.objects.filter(substitute=product, user=user).exists():
                        product.is_favorite = True
                    else:
                        product.is_favorite = False

            context = {
                'obj': obj,
                'title': title,
                'products': products,
            }

            return render(request, self.template_name, context)


class Search(View):
    """
    Handles the search of products in the app.
    Also contains the algorithm that show better products compared to
    the queried product.
    """

    template_name = 'products/search.html'

    def get(self, request):
        """
        Used to handle queries from user and perform a search
        """
        query = request.GET.get('query')

        user = auth.get_user(request)

        if not query:

            # display random products with imgs
            products = (Product.objects.filter(
                nutri_grade="a").exclude(
                    img__isnull=True).exclude(
                    name__icontains="frite").exclude(
                    name__icontains="frie").order_by('?')
            )[:9]

            title = gettext("Suggestion de produits")

            chosen_product = None

        else:
            # title contains the query and query is not sensitive to case.
            products = Product.objects.filter(name__icontains=query)

            if len(products) > 0:
                chosen_product = products[0]

                if chosen_product.nutri_grade == "a":
                    better_products = [
                        product for product in products
                        if product.nutri_grade == chosen_product.nutri_grade
                    ]
                else:
                    better_products = [
                        product for product in products
                        if product.nutri_grade < chosen_product.nutri_grade
                    ]

                products = better_products[:6]

            else:
                chosen_product = None

            # title = gettext(
            #     "Résultats pour la requête {}".format(
            #         query.capitalize()
            #     )
            # )

            title = ""

        # check if user is not anonymous
        if user.username != "":  # pragma: no cover
            for product in products:
                if Favorite.objects.filter(substitute=product, user=user).exists():
                    product.is_favorite = True
                else:
                    product.is_favorite = False

        context = {
            'chosen_product': chosen_product,
            'products': products,
            'title': title,
            'query': query,
        }

        return render(request, self.template_name, context)


class FavoriteView(LoginRequiredMixin, View):
    """
    Handles two things:
    - get: The showing of a user's favorites
    - post: The add/remove products to favorites, via a specific url (bookmark)
    """

    # pass the model in path args in urls.py
    # e.g: FavoriteView.as_view(model=Favorite)

    model = None
    template_name = 'products/favorites.html'

    def get(self, request, product_id=None):
        """
        Get all the favorites of a user
        """

        user = auth.get_user(request)
        favorites = self.model.objects.filter(user=user)

        context = {
            'favorites': favorites
        }

        # get next url
        next_url = request.GET.get('next')

        # redirect to next url
        if next_url:  # pragma: no cover
            return HttpResponseRedirect(next_url)
        else:
            return render(request, self.template_name, context)

    def post(self, request, product_id):
        """
        Adds or remove a product to the connected user's favorites
        """

        # Get the user if connected
        user = auth.get_user(request)

        # Trying to get a favorite from the database, or create a new one
        product = Product.objects.get(pk=product_id)
        favorite, created = self.model.objects.get_or_create(substitute=product, user=user)

        # If no new bookmark has been created,
        # Then we believe that the request was to delete the bookmark
        if not created:
            favorite.delete()

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

nutellove/products/templates/products/shared/chosen_product.html
<!-- Displays a single product -->

{% load static %}

  <!-- display the chosen product -->
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 text-center mb-5 align-bottom p-0">
        <a href="{% url 'products:product_detail' product_id=chosen_product.id %}">

            <div class="contain">
              <div class="img-container" style="background-image: {% if chosen_product.img is none %} url({% static 'img/placeholder.png' %}) {% else %}  url({{ chosen_product.img }}) {% endif %}"></div>
              <div class="text-block text-left">
                <h4 class="superpose-img"><a href="{% url 'products:product_detail' product_id=chosen_product.id %}">{{ chosen_product.name }}</a></h4>
                <ul class="list-inline">
                  {% for brand in chosen_product.brands.all %}
                    {% include 'products/shared/list_brand.html' with product=chosen_product %}
                  {% endfor %}
                </ul>

                {% if chosen_product.nutri_grade == "a" %}
                  <p>Nutriscore : <span class="badge nutri-a text-white">{{ chosen_product.nutri_grade.upper }}</span></p>
                {% elif chosen_product.nutri_grade == "b" %}
                  <p>Nutriscore : <span class="badge nutri-b text-white">{{ chosen_product.nutri_grade.upper }}</span></p>
                {% elif chosen_product.nutri_grade == "c" %}
                  <p>Nutriscore : <span class="badge nutri-c text-dark">{{ chosen_product.nutri_grade.upper }}</span></p>
                {% elif chosen_product.nutri_grade == "d" %}
                  <p>Nutriscore : <span class="badge nutri-d text-white">{{ chosen_product.nutri_grade.upper }}</span></p>
                {% elif chosen_product.nutri_grade == "e" %}
                  <p>Nutriscore : <span class="badge nutri-e text-white">{{ chosen_product.nutri_grade.upper }}</span></p>
                {% endif %}

              </div>
            </div>
        </a>
      </div>
    </div>
  </div>
    <!-- !!end display the chosen product -->

nutellove/products/templates/products/shared/footer.html
<footer class="footer">
    <div class="container">
        <a href="" class="ml-5 text-muted">Mentions légales</a>
        <a href="" class="ml-5 text-muted">Contacts</a>
    </div>
</footer>

nutellove/products/templates/products/shared/header.html
{% load static %}

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand js-scroll-trigger" href="#page-top"><img class="mr-2 align-top" height="30px" src="{% static 'products/img/logo_pur_beurre.svg' %}" alt="">Pur beurre</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="compte"><i class="fa fa-2x fa-user text-primary mb-3 sr-icons"></i></a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="aliments"><img height="35px" src="{% static 'products/img/carrot.svg' %}" alt="Mes aliments"></a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="deconnexion"><i class="fa fa-2x fa-sign-out text-primary mb-3 sr-icons"></i></a>
        </li>
      </ul>
    </div>
  </div>
</nav>

nutellove/products/templates/products/shared/list_brand.html
<!-- Display a list of brands, with conditionnal commas -->

{% if product.brands.all|length_is:"1" %}
  <li class="list-inline-item"><a href="{% url 'products:brand_detail' obj_id=brand.id %}"> {{ brand.name }} </a></li>
{% else %}
  {% if forloop.counter < product.brands.all|length %}
    <li class="list-inline-item"><a href="{% url 'products:brand_detail' obj_id=brand.id %}"> {{ brand.name }}</a>, </li>
  {% else %}
    <li class="list-inline-item"><a href="{% url 'products:brand_detail' obj_id=brand.id %}"> {{ brand.name }}</a> </li>
  {% endif %}
{% endif %}

nutellove/products/templates/products/shared/list_of_brands_categories.html
<!-- Displays a list of products -->

{% load static %}
{% load i18n %}

{% if list_title %}
<h2 class="text-center mb-5 page-title">
  {% comment %}Translators: No product found{% endcomment %}
  {% blocktrans %} {{ list_title }} {% endblocktrans %}
  <hr>
</h2>
{% endif %}

<div class="container-fluid">
  <div class="row">
    <ul>
      

    {% for obj in objs %}

      <!-- display infos about product -->
        {% if forloop.counter < objs|length %}
          <strong><li class="list-inline-item"><a href="{% if model == 'Brand' %}{% url 'products:brand_detail' obj_id=obj.id %} {% elif model == 'Category' %}{% url 'products:category_detail' obj_id=obj.id %}{% endif %}"> {{ obj.name }}</a></strong>, </li>
        {% else %}
          <strong><li class="list-inline-item"><a href="{% if model == 'Brand' %}{% url 'products:brand_detail' obj_id=obj.id %} {% elif model == 'Category' %}{% url 'products:category_detail' obj_id=obj.id %}{% endif %}"> {{ obj.name }}</a> </li></strong>
        {% endif %}

    {% endfor %}
    
    </ul>
  <!-- !!end display infos about product -->
  </div>
</div>

nutellove/products/templates/products/shared/list_of_products.html
<!-- Displays a list of products -->

{% load static %}
{% load i18n %}

{% if list_title %}
<h2 class="text-center mb-5 page-title">
  {% comment %}Translators: No product found{% endcomment %}
  {% blocktrans %} {{ list_title }} {% endblocktrans %}
  <hr>
</h2>
{% endif %}

<div class="container-fluid">
  <div class="row">
    {% for product in products %}
    <!-- display infos about product -->
      <div class="col-xl-4 col-lg-6 col-md-6 col-xs-1 text-center border product-block">
      
      {% if product.nutri_grade == "a" %}
        <div class="nutri-grade"><span class="badge nutri-a text-white">{{ product.nutri_grade.upper }}</span></div>
      {% elif product.nutri_grade == "b" %}
        <div class="nutri-grade"><span class="badge nutri-b text-white">{{ product.nutri_grade.upper }}</span></div>
      {% elif product.nutri_grade == "c" %}
        <div class="nutri-grade"><span class="badge nutri-c text-dark">{{ product.nutri_grade.upper }}</span></div>
      {% elif product.nutri_grade == "d" %}
        <div class="nutri-grade"><span class="badge nutri-d text-white">{{ product.nutri_grade.upper }}</span></div>
      {% elif product.nutri_grade == "e" %}
        <div class="nutri-grade"><span class="badge nutri-e text-white">{{ product.nutri_grade.upper }}</span></div>
      {% endif %}

        <div class="container vbottom p-3">
          <a href="{% url 'products:product_detail' product_id=product.id %}">
            {% if product.img_small is none %}
              <img class="img-responsive" src="{% static 'img/logo_pur_beurre.png' %}" alt="{{ product.name }}">
            {% else %}
              <img class="img-responsive" src="{{ product.img_small }}" alt="{{ product.name }}">
            {% endif %}
          </a>

          <!-- display the name of the product -->
          <h4><a href="{% url 'products:product_detail' product_id=product.id %}">{{ product.name }}</a></h4>

          <!-- display brands for each product, with a comma or not depending on brand index -->
          <ul class="list-inline">
            {% for brand in product.brands.all %}
              <!-- Display brands -->
              {% include 'products/shared/list_brand.html' with product=product %}
            {% endfor %}
          </ul>
          <!-- !!end display brands for each product -->

          
          <div class="favs mt-2">
            <!-- pass product_id to the url, to use it in the view and push it to db -->
            <form action="{% url 'products:bookmark' product_id=product.id %}?next={{request.path}}" method="post">
              {% csrf_token %}
              {% if not product.is_favorite %}
                <button type="submit" class="btn btn-danger" value="{{ product.id }}">
                  {% blocktrans %}Ajouter aux favoris{% endblocktrans %}
                  <i class="fa fa-heart"></i>
                </button>

              {% else %}
                <button type="submit" class="btn btn-secondary" value="{{ product.id }}">
                  {% blocktrans %}Retirer des favoris{% endblocktrans %}
                  <i class="fa fa-minus-square"></i>
                </button>

              {% endif %}
            </form>
          </div>

        </div>

      </div>
    {% endfor %}
  <!-- !!end display infos about product -->
  </div>
</div>